name: FactionsUltimate
version: 1.5
main: me.changelin.factions.FactionsPlugin
api-version: '1.20'
author: Changelin
softdepend: [PlaceholderAPI, Vault]
commands:
  f:
    description: Commande principale des factions
    aliases: [faction, F, FACTION]
